fixed DECam config file
skyportal/gwemopt pull request #151
Opened 2023-09-24 20:05 UTC by igorandreoni

I made these fixes:

- the available filters are ugrizy, not only r
- horizon key was repeated
- slew rate and overheads were incorrect

2023-09-24 20:09 UTC, mcoughlin requested changes
Just leave it as r, otherwise good. We would need to build in more capabilities to have multiple filter, magnitude and exposure time keys.

2023-09-24 20:09 UTC, mcoughlin commented on gwemopt/data/config/DECam.config
> +filt ugrizy
We use one filter to just scale limiting magnitudes

2023-09-24 20:23 UTC, igorandreoni commented on gwemopt/data/config/DECam.config
> +filt ugrizy
done

2023-09-24 21:43 UTC, mcoughlin commented
@igorandreoni Looks like the test output files need to be updated with this. https://github.com/skyportal/gwemopt/blob/main/gwemopt/tests/test_schedule.py#L62
@robertdstein had left an example here.

2023-11-24 22:52 UTC, mcoughlin approved these changes
Merging. Tests confuse me a bit.

2023-11-24 22:52 UTC, merged